name: SciChap CI
on:
  push:
  release:
  schedule:
    - cron: "0 2 * * *"
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # whatever's not 'deprecated' on Spack
        chapel-version: ['2.6.0', '2.5.0', '2.4.0']
    container:
      image: chapel/chapel:${{ matrix.chapel-version }}
    steps:
      - name: Checkout SciChap
        id: checkout
        uses: actions/checkout@v5
      - name: Using Chapel ${{ matrix.chapel-version }}, building package...
        id: build
        run: mason build -- --checks --warnings --debug
      - name: Running tests with Mason...
        id: test
        run: mason test --show
      - name: Running chplcheck...
        id: code-check
        # TODO: remove --disable-rule after dropping chapel 2.4.0 support
        run: chplcheck --disable-rule CamelCaseFunctions $(find . -type f -iname "*.chpl")
