name: SciChap CI
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chapel-version: ['2.6.0']
    container:
      image: chapel/chapel:${{ matrix.chapel-version }}
    steps:
      - uses: actions/checkout@v5
      - name: Using Chapel ${{ matrix.chapel-version }}, building package...
        run: mason build
      - name: Running tests with Mason...
        run: mason test --show
      - name: Building docs with chpldoc...
        run: mason doc