name: SciChap CI
on:
  push:
  release:
  schedule:
    - cron: "0 2 * * *"
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # whatever's not 'deprecated' on Spack
        chapel-version: ['latest', '2.5.0', '2.4.0']
    container:
      image: chapel/chapel:${{ matrix.chapel-version }}
    steps:
      - name: Checkout SciChap
        id: checkout
        uses: actions/checkout@v5
      - name: Using Chapel ${{ matrix.chapel-version }}, building package...
        id: build
        run: mason build -- --checks --warnings --debug
      - name: Running tests with Mason...
        id: test
        run: mason test --show
      - name: Building docs with chpldoc...
        id: build-doc
        run: mason doc
      - name: Upload artifacts...
        if: ${{ matrix.chapel-version == 'latest' }}
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          name: doc-latest
          path: doc/
  deploy:
    if: github.ref == 'ref/heads/master'
    needs: build-test

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: doc-latest
